BWL.Model.AccessRequest = {
	Type : 'AccessRequest',
	CanRespond : false,
	Key : null,
	RequestedAccess : null,
	RequestedBy : null,
	RequestedByKey : null,
	RequestedByName : null,
	RequestedItem : null,
	RequestSentToKeys : null,
	Response : null,
	ResponseFrom : null,
	ResponseFromKey : null
};
BWL.Model.AccountProfile = {
	Type : 'AccountProfile',
	Active : false,
	DomainProfile : null,
	Email : null,
	EmailVerified : false,
	FullName : null,
	Key : null,
	PasswordHash : null,
	RequestedRole : null
};
BWL.Model.Address = {
	Type : 'Address',
	AddressLine1 : null,
	AddressLine2 : null,
	AddressType : null,
	City : null,
	Country : null,
	County : null,
	District : null,
	IsConfirmed : false,
	Key : null,
	Latitude : 0,
	Longitude : 0,
	PostalCode : null,
	Region : null,
	Timezone : null
};
BWL.Model.APIResponse = {
	Type : 'APIResponse',
	Code : null,
	DiagnosticsMatrix : null,
	ExecutionSeconds : 0,
	Message : null,
	Object : null,
	ServerDateTime : null
};
BWL.Model.Cart = {
	Type : 'Cart',
	Currency : null,
	ExpiryDateTime : null,
	Fees : null,
	InventoryItems : null,
	Key : null,
	Payment : null,
	ProfileKey : null,
	RequiresShipping : false,
	Shipping : null,
	ShippingAddress : null,
	State : null,
	SubTotal : null,
	Taxes : null,
	Total : null
};
BWL.Model.Category = {
	Type : 'Category',
	ChildCategories : null,
	CustomURI : null,
	Description : null,
	DisplayOrder : 0,
	Image : null,
	Key : null,
	Name : null,
	ParentCategoryKey : null,
	RankingScore : 0,
	SmallImage : null
};
BWL.Model.City = {
	Type : 'City',
	CountryISO : null,
	geonameId : null,
	Key : null,
	Latitude : 0,
	Longitude : 0,
	Name : null,
	NameUpper : null,
	NameUTF8 : null,
	Population : 0,
	Region : null,
	RegionCode : null,
	RegionISO : null,
	Timezone : null,
	TimezoneName : null
};
BWL.Model.ClientApplicationInfo = {
	Type : 'ClientApplicationInfo',
	Key : null,
	Name : null,
	Secret : null
};
BWL.Model.Contact = {
	Type : 'Contact',
	Addresses : null,
	AlternativePhone : null,
	CompanyName : null,
	ContactRole : null,
	DateOfBirth : null,
	EmailAddress : null,
	Facsimile : null,
	FullName : null,
	Gender : null,
	Image : null,
	Key : null,
	Phone : null,
	PreferredName : null,
	WebAddress : null
};
BWL.Model.ContainerConfiguration = {
	Type : 'ContainerConfiguration',
	ConfigurationKey : null,
	Host : null,
	Key : null,
	Value : null
};
BWL.Model.Continent = {
	Type : 'Continent',
	geonameId : null,
	ISO : null,
	Key : null,
	Name : null
};
BWL.Model.Copyright = {
	Type : 'Copyright',
	Contacts : null,
	HolderName : null,
	Key : null
};
BWL.Model.Country = {
	Type : 'Country',
	AreaSqKM : 0,
	Capital : null,
	ContinentISO : null,
	CurrencyCode : null,
	CurrencyName : null,
	Fips : null,
	geonameId : null,
	HasCities : false,
	HasPostalCodes : false,
	HasRegions : false,
	ISO : null,
	ISO3 : null,
	ISONumeric : null,
	Key : null,
	Languages : null,
	Name : null,
	Neighbours : null,
	Phone : null,
	Population : 0,
	PostalCodeFormat : null,
	PostalCodeRegex : null,
	TLD : null
};
BWL.Model.Currency = {
	Type : 'Currency',
	DecimalPlaces : 0,
	DecimalSeparator : null,
	HTMLCharacter : null,
	ISO : null,
	Key : null,
	Name : null,
	PrefixCharacter : false,
	ThousandsSeparator : null,
	ToUSDConversionRate : 0,
	UnicodeCharacter : null
};
BWL.Model.CustomURI = {
	Type : 'CustomURI',
	Key : null,
	URI : null
};
BWL.Model.CustomURIInfo = {
	Type : 'CustomURIInfo',
	ItemKey : null,
	ItemType : null,
	StoreKey : null,
	URI : null
};
BWL.Model.DefaultAdminProviderInfo = {
	Type : 'DefaultAdminProviderInfo',
	ProviderId : null,
	ProviderType : null
};
BWL.Model.DigitalSource = {
	Type : 'DigitalSource',
	BaseURL : null,
	Copyright : null,
	Description : null,
	Filename : null,
	FileSize : 0,
	Key : null,
	MimeInfo : null,
	Name : null,
	SourceFile : null
};
BWL.Model.DomainProfile = {
	Type : 'DomainProfile',
	AccessToken : null,
	AccountProfile : null,
	Contact : null,
	DomainProfileId : 0,
	Key : null,
	LastLogoff : null,
	LastLogon : null,
	MembershipProfile : null,
	ProfileRole : null,
	SocialProfiles : null
};
BWL.Model.Event = {
	Type : 'Event',
	Categories : null,
	ChildEvents : null,
	Contacts : null,
	CustomURI : null,
	Description : null,
	DisplayOrder : 0,
	EndTime : null,
	Items : null,
	Key : null,
	LargeImages : null,
	MaximumCapacity : 0,
	Name : null,
	OnSaleDateTimeEnd : null,
	OnSaleDateTimeStart : null,
	Places : null,
	Public : false,
	RankingScore : 0,
	SearchPriority : 0,
	ShowCountdown : false,
	SmallImage : null,
	StartTime : null,
	WebLinks : null
};
BWL.Model.Facebook = {
	Type : 'Facebook',
	Description : null,
	FacebookType : null,
	Key : null,
	Name : null,
	ProviderId : null
};
BWL.Model.Fee = {
	Type : 'Fee',
	Amount : 0,
	Key : null,
	Name : null
};
BWL.Model.File = {
	Type : 'File',
	BaseURL : null,
	Copyright : null,
	Description : null,
	Filename : null,
	FileSize : 0,
	Key : null,
	MimeInfo : null,
	Name : null,
	SourceFile : null
};
BWL.Model.Flickr = {
	Type : 'Flickr',
	Description : null,
	Key : null,
	Name : null,
	ProviderId : null
};
BWL.Model.GeneralAdmissionTicketInventoryItem = {
	Type : 'GeneralAdmissionTicketInventoryItem',
	CartItemKey : null,
	DownloadLink : null,
	Info : null,
	IsLocked : false,
	IsSold : false,
	ItemInfoKey : null,
	ItemInfoPrice : null,
	ItemInfoType : null,
	Key : null,
	LockExpiryDateTime : null,
	LockingDomainProfileKey : null,
	ScanDateTime : null,
	ScanDeviceKey : null,
	SoldDateTime : null,
	SoldToDomainProfileKey : null,
	UIID : 0
};
BWL.Model.GeneralAdmissionTicketItemInfo = {
	Type : 'GeneralAdmissionTicketItemInfo',
	Categories : null,
	CustomURI : null,
	Description : null,
	DisplayOrder : 0,
	IsTaxable : false,
	Items : null,
	Key : null,
	LargeImages : null,
	MaxPurchaseQuantity : 0,
	Name : null,
	NumberTotal : 0,
	OnSaleDateTimeEnd : null,
	OnSaleDateTimeStart : null,
	Policy : null,
	PreviewImages : null,
	Price : null,
	PricingParent : null,
	PricingTiers : null,
	Public : false,
	RankingScore : 0,
	SalePrice : null,
	SalePriority : 0,
	SearchPriority : 0,
	ShowCountdown : false,
	SmallImage : null,
	TaxRules : null,
	TicketTemplate : null,
	Unlimited : false
};
BWL.Model.Genre = {
	Type : 'Genre',
	Description : null,
	Key : null,
	Name : null
};
BWL.Model.Image = {
	Type : 'Image',
	BaseURL : null,
	Copyright : null,
	Description : null,
	DPI : 0,
	Filename : null,
	FileSize : 0,
	HeightPX : 0,
	ImageFile : null,
	Key : null,
	MimeInfo : null,
	Name : null,
	SourceFile : null,
	ThumbFile : null,
	WidthPX : 0
};
BWL.Model.ImageCropResize = {
	Type : 'ImageCropResize',
	CropHeight : 0,
	CropWidth : 0,
	CropX : 0,
	CropY : 0,
	ImageHeight : 0,
	ImageWidth : 0,
	RequiredHeight : 0,
	RequiredWidth : 0
};
BWL.Model.InitializePayload = {
	Type : 'InitializePayload',
	ClientApplications : null,
	ContainerConfigurations : null,
	DefaultAdminInfos : null
};
BWL.Model.InventoryStats = {
	Type : 'InventoryStats',
	ItemKey : null,
	ItemType : null,
	NumberAvailable : 0,
	NumberLocked : 0,
	NumberSold : 0,
	NumberTotal : 0
};
BWL.Model.ISOName = {
	Type : 'ISOName',
	ISO : null,
	Name : null
};
BWL.Model.KeyName = {
	Type : 'KeyName',
	Key : null,
	Name : null
};
BWL.Model.LastFM = {
	Type : 'LastFM',
	Description : null,
	Key : null,
	LastFMType : null,
	Name : null,
	ProviderId : null
};
BWL.Model.LinkedIn = {
	Type : 'LinkedIn',
	Description : null,
	Key : null,
	LinkedInType : null,
	Name : null,
	ProviderId : null
};
BWL.Model.MembershipProfile = {
	Type : 'MembershipProfile',
	DomainProfile : null,
	Email : null,
	FullName : null,
	Key : null,
	PasswordHash : null
};
BWL.Model.Message = {
	Type : 'Message',
	Body : null,
	From : null,
	FromName : null,
	MessageLevel : null,
	MessageProvider : null,
	MessageType : null,
	StoreKey : null,
	Subject : null,
	To : null,
	ToName : null
};
BWL.Model.MimeInfo = {
	Type : 'MimeInfo',
	Extention : null,
	FullMIMEType : null,
	MIMESubType : null,
	MIMEType : null,
	Order : 0
};
BWL.Model.MySpace = {
	Type : 'MySpace',
	Description : null,
	Key : null,
	Name : null,
	ProviderId : null
};
BWL.Model.oAuthAccessToken = {
	Type : 'oAuthAccessToken',
	ClientIP : null,
	ClientKey : null,
	DisplayType : null,
	Key : null,
	ProviderId : null,
	ProviderType : null,
	SessionKey : null,
	State : null
};
BWL.Model.oAuthInfo = {
	Type : 'oAuthInfo',
	AuthURL : null,
	SessionKey : null
};
BWL.Model.oAuthSession = {
	Type : 'oAuthSession',
	ClientIP : null,
	ClientKey : null,
	DisplayType : null,
	Key : null,
	ProviderAccessSecret : null,
	ProviderAccessToken : null,
	ProviderAccessVerifier : null,
	ProviderId : null,
	ProviderRequestSecret : null,
	ProviderRequestToken : null,
	ProviderType : null,
	RedirectURL : null,
	SessionType : null,
	State : null
};
BWL.Model.Order = {
	Type : 'Order',
	Contact : null,
	Currency : null,
	DomainProfileKey : null,
	Fees : null,
	Fulfilled : null,
	InventoryItems : null,
	Key : null,
	OrderId : 0,
	Placed : null,
	RequiresShipping : false,
	Shipped : null,
	Shipping : null,
	ShippingAddress : null,
	State : null,
	StoreKey : null,
	SubTotal : null,
	Taxes : null,
	Total : null,
	Transactions : null
};
BWL.Model.PaymentInfo = {
	Type : 'PaymentInfo',
	SessionKey : null,
	StartPaymentURL : null,
	StoreKey : null
};
BWL.Model.PaymentProvider = {
	Type : 'PaymentProvider',
	Currency : null,
	Key : null,
	Policy : null,
	ProviderId : null,
	ProviderToken : null,
	ProviderType : null
};
BWL.Model.PaymentProviderInfo = {
	Type : 'PaymentProviderInfo',
	CurrencyList : null,
	ProviderIdText : null,
	ProviderName : null,
	ProviderTokenText : null,
	ProviderType : null,
	RequiresProviderId : false,
	RequiresProviderToken : false
};
BWL.Model.PaymentSession = {
	Type : 'PaymentSession',
	Amount : null,
	AuthToken : null,
	CartKey : null,
	ClientIP : null,
	DisplayType : null,
	Key : null,
	Message : null,
	PaymentSessionId : 0,
	ProfileKey : null,
	ProviderReceipt : null,
	ProviderType : null,
	RedirectURL : null,
	State : null,
	StoreKey : null
};
BWL.Model.Place = {
	Type : 'Place',
	Address : null,
	Contacts : null,
	CustomURI : null,
	Description : null,
	DisplayOrder : 0,
	Key : null,
	LargeImages : null,
	Name : null,
	Public : false,
	RankingScore : 0,
	SearchPriority : 0,
	SmallImage : null
};
BWL.Model.PostalCode = {
	Type : 'PostalCode',
	CityName : null,
	Code : null,
	CountryISO : null,
	County : null,
	District : null,
	Key : null,
	Latitude : 0,
	Longitude : 0,
	Region : null,
	RegionISO : null
};
BWL.Model.Price = {
	Type : 'Price',
	Currency : null,
	ItemPrice : 0
};
BWL.Model.QueuedMessage = {
	Type : 'QueuedMessage',
	Body : null,
	From : null,
	FromName : null,
	MessageLevel : null,
	MessageProvider : null,
	MessageType : null,
	NextRetryDateTime : null,
	RetryCount : 0,
	StoreKey : null,
	Subject : null,
	To : null,
	ToName : null
};
BWL.Model.Region = {
	Type : 'Region',
	Code : null,
	Country : null,
	CountryISO : null,
	geonameId : null,
	ISO : null,
	Key : null,
	Name : null
};
BWL.Model.RegionSet = {
	Type : 'RegionSet',
	Key : null,
	Name : null,
	Regions : null
};
BWL.Model.ScanDevice = {
	Type : 'ScanDevice',
	Active : false,
	Description : null,
	DeviceInfo : null,
	Events : null,
	Key : null,
	LastSyncDateTime : null,
	Name : null
};
BWL.Model.ScanDeviceInfo = {
	Type : 'ScanDeviceInfo',
	Hardware : null,
	Name : null,
	OS : null,
	UniqueID : null,
	Version : null
};
BWL.Model.ScanEventInfo = {
	Type : 'ScanEventInfo',
	EventDateTime : null,
	Key : null,
	Name : null,
	PlaceName : null
};
BWL.Model.ScanTicket = {
	Type : 'ScanTicket',
	Info : null,
	Key : null,
	ScanDateTime : null,
	ScanDeviceKey : null,
	SyncDateModified : null,
	TicketInfoKey : null,
	Valid : false,
	ValidationHash : null
};
BWL.Model.ScanTicketInfo = {
	Type : 'ScanTicketInfo',
	Key : null,
	Name : null
};
BWL.Model.SearchIndex = {
	Type : 'SearchIndex',
	Categories : null,
	Description : null,
	IsSalePrice : false,
	ItemDateModified : null,
	ItemKey : null,
	ItemType : null,
	Key : null,
	Locations : null,
	Name : null,
	Price : null,
	SearchPriority : 0,
	SearchTags : null,
	SearchText : null,
	StoreKey : null,
	URI : null
};
BWL.Model.ServiceInvoice = {
	Type : 'ServiceInvoice',
	Amount : null,
	InvoiceCreated : null,
	InvoiceDue : null,
	InvoicePaid : null,
	Key : null,
	ServiceInvoiceId : 0,
	ServiceInvoiceItems : null,
	State : null,
	StoreKey : null
};
BWL.Model.ServiceInvoiceItem = {
	Type : 'ServiceInvoiceItem',
	Amount : null,
	BandwidthUsed : 0,
	DomainProfileKey : null,
	Key : null,
	OrderKey : null,
	OrderPlaced : null,
	OrderValue : null,
	State : null,
	StoreKey : null
};
BWL.Model.SocialProfile = {
	Type : 'SocialProfile',
	EmailAddress : null,
	FullName : null,
	Key : null,
	ProviderAccessSecret : null,
	ProviderAccessToken : null,
	ProviderId : null,
	ProviderType : null,
	PublicImageURL : null,
	PublicProfileURL : null
};
BWL.Model.Store = {
	Type : 'Store',
	Address : null,
	Categories : null,
	Contacts : null,
	Currency : null,
	Description : null,
	Events : null,
	ExternalInfos : null,
	HasMemberships : false,
	HasWishlist : false,
	IsOwner : false,
	Items : null,
	Key : null,
	LargeBannerImages : null,
	LargeImages : null,
	Name : null,
	PaymentProviders : null,
	Public : false,
	SearchPriority : 0,
	SmallBannerImage : null,
	SmallImage : null,
	StoreURIs : null,
	TaxRules : null,
	WebLinks : null
};
BWL.Model.StoreConfiguration = {
	Type : 'StoreConfiguration',
	ConfigurationKey : null,
	Key : null,
	StoreKey : null,
	Value : null
};
BWL.Model.StorePreRegister = {
	Type : 'StorePreRegister',
	AddressLine1 : null,
	AddressLine2 : null,
	City : null,
	ContactName : null,
	Country : null,
	County : null,
	District : null,
	EmailAddress : null,
	Facebook : null,
	Key : null,
	Latitude : 0,
	LinkedIn : null,
	Longitude : 0,
	Name : null,
	Phone : null,
	PostalCode : null,
	Region : null,
	StoreKey : null,
	StoreURI : null,
	Timezone : null,
	Twitter : null,
	WebAddress : null
};
BWL.Model.StoreURI = {
	Type : 'StoreURI',
	Key : null,
	URI : null
};
BWL.Model.Tax = {
	Type : 'Tax',
	Code : null,
	IsTaxonTax : false,
	Key : null,
	Name : null,
	Number : null,
	Percent : 0
};
BWL.Model.TaxRule = {
	Type : 'TaxRule',
	CityKey : null,
	CountryKey : null,
	Key : null,
	RegionKey : null,
	Taxes : null
};
BWL.Model.TicketTemplate = {
	Type : 'TicketTemplate',
	BackgroundColorHex : null,
	CustomTemplateImage : null,
	FontColorHex : null,
	FontType : null,
	Horizontal : false,
	IncludeDetails : false,
	IncludeQRCode : false,
	IncludeSeatInfo : false,
	IncludeTerms : false,
	IncludeTicketImage : false,
	IncludeTicketName : false,
	Key : null,
	Template : null
};
BWL.Model.Timezone = {
	Type : 'Timezone',
	CountryISO : null,
	DSTOffset : 0,
	GMTOffset : 0,
	Key : null,
	Name : null,
	RawOffset : 0
};
BWL.Model.Transaction = {
	Type : 'Transaction',
	Amount : null,
	Key : null,
	Message : null,
	ProviderReceipt : null,
	ProviderType : null,
	State : null,
	TransactionId : 0
};
BWL.Model.Twitter = {
	Type : 'Twitter',
	Description : null,
	Key : null,
	Name : null,
	ProviderId : null
};
BWL.Model.WebLink = {
	Type : 'WebLink',
	Description : null,
	Key : null,
	Name : null,
	URL : null
};
BWL.Model.Wishlist = {
	Type : 'Wishlist',
	Items : null,
	Key : null,
	ProfileKey : null
};
BWL.Model.YouTube = {
	Type : 'YouTube',
	Description : null,
	Key : null,
	Name : null,
	ProviderId : null
};
