var AddressResources = {
    LabelPostalCode : 'Postal Code *', 
    LabelZipCode: 'Zip Code *',
    LabelPostalCodeHelp : 'The postal code for the administrator',
    LabelZipCodeHelp: 'The zip code for the administrator',
    LabelAddressType: 'Address Type',
    LabelCountry: 'Country',
    LabelProvince: 'Province',
    LabelState: 'State',
    LabelAreYouSureRemove: 'Are you sure you would like to remove this address from the contact ?',
    LabelAddAddress: 'Add Address',
    Field_PostalCode: 'Postal Code',
    Field_PostalCodeUS: 'Zip Code',
    Field_PostalCodeGB: 'Post Code',
    Field_PostalCode_Help: ['The postal code for the administrator', 'The zip code for the administrator'],
    Error_IncorrectPostalCode: 'Please enter a valid Postal Code.',
    Error_IncorrectPostalCodeUS: 'Please enter a valid Zip Code.',
    Error_IncorrectPostalCodeGB: 'Please enter a valid Post Code.',
    Error_EmptyPostalCode: 'Please enter a value before doing a search.',
    Error_MissData : 'Please enter full data for address.',
    LabelTimezone: 'Time Zone'
}