// ////////////////////////////////////////////////
//
// ATs UI - Layouts/Languages/English/resources/common.js
//
// Copyright 2012 AzureTickets Enterprises Inc.
// All rights reserved
// http://www.azuretickets.info
//
// ////////////////////////////////////////////////

var CommonResources = {
  Text_ValidationErrors : 'Some errors were found while processing your request. Please review and resend.',
  Text_RequiredField : 'The field {0} is required',
  Text_AddRecipient : 'Add Recipient',
  Text_Sendemail : 'Send email',
  Text_Sender : 'SENDER',
  Text_Recipient : 'RECIPIENT',
  Text_EmailToFriend : 'Email to Friend',
  Text_EmailAddress : 'Email Address',
  Text_Message : "Message",
  Text_Close : 'Close',
  Text_Next : 'Next',
  Text_Back : 'Back',
  Text_To : "To",
  Text_From : "From",
  Text_Print : "Print",
  Text_Showmap : "show map",
  Text_Confirmation : 'Confirmation',
  Text_GetRoute : "Get Route",
  Text_Bingmap : "Bing map",
  Text_NotFindLocation : "Can't find the location",
  Text_NoRouteFound : "No Route found",
  Text_Create : 'Create',
  Text_Color : 'Color',
  Text_Agreement : 'Service Agreement',
  Text_Add : 'Add',
  Text_Save : 'Save',
  Text_SaveSettings : 'Save Settings',
  Text_Edit : 'Edit',
  Text_Update : "Update",
  Text_Cancel : "Cancel",
  Text_Remove : "Remove",
  Text_Search : 'Search',
  Text_Search_here : 'Search here.........',
  Text_IAccept : 'I Accept',
  Text_Name : 'Name',
  Text_Item : 'Item',
  Text_Password : 'Password',
  Text_RePassword : 'Re-enter Password',
  Text_ChangeImage : 'Change Image',
  Text_Each : 'Each',
  Text_Qty : 'Qty',
  Text_View : 'View',
  Text_List : 'List',
  Text_Grid : 'Grid',
  Text_Ticket : 'Ticket',
  Text_SortBy : 'Sort by',
  Text_PageOf : 'Page {0} of {1}',
  Text_MostPopular : 'Most Popular',
  Text_Price_Asc : 'Price: Low to High',
  Text_Price_Desc : 'Price: High to Low',
  Text_Name_Asc : 'Name: A-Z',
  Text_Name_Desc : 'Name: Z-A',
  Text_MaximumEmailAllow : "Maximum {0} email addresses allowed",
  Text_DateNewest : 'Date: Newest First',
  Text_DateOldest : 'Date: Oldest First',
  Text_FirstToReviews : 'Be the first to review this product',
  Text_AddToCart : 'Add to Cart',
  Text_LearnMore : 'Learn More',
  Text_NoProduct : 'There are no products matching the selection.',
  Text_EmailToFriend : 'Email to a Friend',
  Text_AddToWishlist : 'Add to Wishlist',
  Text_Previous : 'Previous',
  Text_Next : 'Next',
  Text_TrackList : 'Track List',
  Text_QtyInformation : 'Sale Information',
  Text_OutOfStock : 'Out of Stock',
  Text_Store_Catalog : 'Store Catalog',
  Text_ChooseOption : 'Choose option...',
  Text_DigitalDownload : 'Digital Download',
  Error_System : 'There was a system error: "{0}", please refresh your browser and try again',
  Text_Store : 'Store',
  Text_StoreName : 'Store\'s Name',
  Text_StoreType : 'Your Store',
  Text_StoreCurrency : 'Currency',
  Text_StoreCreate : 'You haven\'t created a store yet. Please follow these registration steps.',
  Text_Description : 'Description',
  Text_InvalidPattern : 'The format for {0} is not valid',
  LabelStoreType : 'Store',
  LabelStoreCurrency : 'Currency',
  LabelStorePaymentProvider : 'Payment Provider',
  LabelStoreName : 'Store\'s Name',
  LabelStoreDescription : 'Description of this Store',
  LabelPlaceName : 'Venue\'s Name',
  LabelPlaceDescription : 'Description of this Venue',
  LabelEventOnSaleDateTimeStart : 'Tickets Sales Starts On',
  LabelEventOnSaleDateTimeEnd : 'Tickets Sales Ends On',
  LabelEventStartTime : 'This Event Starts On',
  LabelEventEndTime : 'This Event Ends On',
  LabelEventName : 'Name for this Event',
  LabelGeneralAdmissionTicketItemInfoName : 'Ticket\'s Name',
  LabelGeneralAdmissionTicketItemInfoOnSaleDateTimeStart : 'Sales Starts On',
  LabelGeneralAdmissionTicketItemInfoOnSaleDateTimeEnd : 'Sales Ends On',
  LabelGeneralAdmissionTicketItemInfoPolicy : 'Policy',
  LabelGeneralAdmissionTicketItemInfoMaxPurchaseQuantity : 'Maximum Allowed Quantity',
  Text_StoreMenu_StoreDetailBt : 'Store Details',
  Text_StoreMenu_Categories : 'Categories',
  Text_StoreMenu_CreateCate : 'Create Category',
  Text_StoreMenu_CreateSubCate : 'Create Sub Category',
  Text_StoreMenu_PaymentSettings : 'Payment Settings',
  Text_StoreMenu_Provider : 'Social Network Providers',
  Text_StoreMenu_PaymentProvider : 'Payment Providers',
  Text_StoreMenu_AddPaymentProvider : 'Add Payment Providers',
  Text_MediaLibraryMenu_MediaLibrary : 'Media',
  Text_ProfileMenu_Profiles : 'Profiles',
  Text_ProfileMenu_CreateProfile : 'Create Profile',
  Text_EventMenu_Events : 'Events',
  Text_EventMenu_CreateEvent : 'Create Event',
  Text_TicketMenu_Tickets : 'Tickets',
  Text_TicketMenu_CreateTicket : 'Create Ticket',
  Text_MerchandiseMenu_Merchandise : 'Products',
  Text_MerchandiseMenu_AddMerchandise : 'Add Products',
  Text_ScannerMenu_Scanner : 'Scanners',
  Text_VenueMenu_Venue : 'Venues',
  Text_DashboardMenu_Dashboard : 'Dashboard',
  Text_VenueEmpty : 'No venues were found for your store',
  Text_TicketEmpty : 'No tickets were found for this event',
  Text_FansMenu_Fans : 'Fans',
  Text_AboutMenu : 'About',
  Text_ShippingInfo : 'Shipping Information',
  Text_OrdersMenu_Orders : 'Orders',
  Text_ReportMenu_Reports : 'Reports',
  Text_Confirm : 'To finish, review and save your changes.',
  Text_ConfirmCloseDialog : 'You are about to close this window, all unsaved information will be lost.\nPress Cancel to go back to previous screen or OK to close the window.',
  Text_NoImageInLibrary : 'Currently there are no image files in the library.',
  Text_NoAudioInLibrary : 'Currently there are no audio files in the library.',
  Text_NoVideoInLibrary : 'Currently there are no video files in the library.',
  Text_NoFileInLibrary : 'Currently there are no files in the library.',
  Text_NoItemInLibrary : 'Currently there are no items in the library.',
  Text_NoOrderInYourAccount : 'Currently there are no order in your account.',
  Text_RemovePaymentProvider : 'Are you sure want to remove this payment provider?',
  Text_RemoveAddress : 'Are you sure want to remove this address?',
  Text_RemoveImage : 'Are you sure want to remove this image?',
  Text_RemoveAccount : 'Are you sure want to remove this account?',
  Text_RemoveWebLink : 'Are you sure want to remove this web link?',
  Text_RemoveTrackFromCD : 'Are you sure want to remove this track?',
  Text_RemoveTrailerFromBluRay : 'Are you sure want to remove this trailer?',
  Text_RemoveAudioGallery : 'Are you sure want to remove this item?',
  Text_ProductOutOfStock : 'This product is out of stock.',
  Text_ErrorCheckingInventory : 'Error on checking inventory.\nPlease try again.',
  Text_CartMessage : 'Drag items here to add to cart',
  Text_RequireLogin : 'In order to add items to the cart you must be logged in.',
  Text_LogOffMsg : 'You have been logged off',
  Text_RegisterMsg : 'You have successfully created your account. Please check your inbox for $0 in order to verify your account.',
  Text_VerifyAccountMsg : 'Please check your email to verified your account.',
  Text_CreateAccountFailedMsg : 'Unable to create account. Please try again.',
  Text_ResetPasswordMsg : 'Password reset request sent to email address.',
  Text_ResetPasswordErrorMsg : 'Could not send reset password request.',
  Text_RemoveProduct : 'Are you sure want to remove this item?',
  Text_RemoveImage : 'Are you sure want to remove this image?',
  Text_RemoveCatetory : 'Are you sure want to remove this category?',
  Text_RemoveProfile : 'Are you sure want to remove this profile?',
  Text_PreviewTicketTemplateMsg : 'Set your template options and click preview.',
  Text_PublicItem : 'Are you sure you want to make this item public?',
  Text_PrivateItem : 'Are you sure you want to make this item private?',
  Text_PublicStore : 'Are you sure you want to make this store public?',
  Text_PrivateStore : 'Are you sure you want to make this store private?',
  Text_State : [
      'Currently Public, Make Private', 'Currently Private, Make Public',
      '(Private)', '(Public)'
  ],
  Text_Status : 'Status',
  Text_MsgPaymentCancel : 'Payment has been canceled',
  Text_MsgPaymentDecline : 'Payment is Declined',
  Text_MsgPaymentError : 'Payment Error',
  Text_MsgProcessError : 'Error processing your order.',
  Text_MsgProcessCompleted : 'Order Completed',
  Text_ChooseStoreThumbImage : 'Are you sure you would like to replace the current image?',
  Text_ProductDescription : 'Product Description',
  Text_BrowserNotSuportHTML5 : 'Your browser is not support play audio',
  Text_VideoProcessing : 'This audio file is being processed, please check back later',
  Text_OrderStateNone : 'None',
  Text_OrderStateNew : 'New',
  Text_OrderStateProcessing : 'Processing',
  Text_OrderStateBackordered : 'Backordered',
  Text_OrderStateOrdered : 'Ordered',
  Text_OrderStateShipped : 'Shipped',
  Text_OrderStateReturned : 'Returned',
  Text_OrderStateFullfiled : 'Fullfiled',
  Text_OrderStateClosed : 'Closed',
  Text_OrderNumber : 'Order #',
  Text_OrderDate : 'Order Date',
  Text_Total : 'Total',
  Text_FilterByDate : 'Filter by Date',
  Text_FilterBy : 'Filter by',
  Text_DateRange : 'Date Range',
  Text_TotalOrders : 'Total Order(s)',
  Text_TotalItems : 'Total Item(s)',
  Text_NoOrdersFound : 'No orders found.',
  Text_Today : 'Today',
  Text_Last7Days : 'Last 7 Days',
  Text_Last30Days : 'Last 30 Days',
  Text_Last90Days : 'Last 90 Days',
  Text_ThisMonth : 'This Month',
  Text_LastMonth : 'Last Month',
  Text_Last3Month : 'Last Three Months',
  Text_ThisYear : 'This Year',
  Text_Custom : 'Custom',
  Text_StoreOrders : 'Store\'s Orders',
  Text_OrderState : "Order State",
  Text_OrderDetail : "Order Detail",
  Text_DatePlaced : "Date Placed",
  Text_DateShipped : "Date Shipped",
  Text_DateFulfilled : "Date Fulfilled",
  Text_PrintOrder : "Print Order",
  Text_PrintThisPage : "Print This Page",
  Text_ClickToSave : "Click to Save",
  Text_ClickToPrint : "Click to Print",
  Text_PastOrders : "Past Orders",
  Text_UpcomingEvents : "Upcoming Events",
  Text_Event : "Event",
  Text_Venue : 'Venue',
  Text_VenueName : 'Venue\'s Name',
  Text_Date : "Date",
  Text_StartDate : "Start Date",
  Text_EndDate : "End Date",
  Text_EventName : "Event Name",
  Text_EventDate : "Event Date",
  Text_Price : "Price",
  Text_SalePrice : "Sale Price",
  Message_UpdateOrderState : 'Order #: {0} updated state! <br /> Status changed: from {1} to {2}',
  Message_SelectOrderItemToPrint : 'Please select at least one item to print',
  Message_YourProfileIsEmpty : 'Can not login. Server return empty profile.',
  Message_CreateOrUseStore : 'Create a new Store or use an existing Store?',
  Text_Loading : 'Loading...',
  Text_Waiting : 'Please Wait...',
  Text_OnlyOutOfStockAccept : 'Only products in stock have been added to your shopping cart',
  Text_EventStartAt : 'Event Starts at',
  Text_EnjoyEvent : "Enjoy the event.",
  Text_PrintTicket : "Print Ticket",
  Text_CreateTicket : "Create Ticket",
  Text_TicketName : "Ticket Name",
  Text_TicketStatus : "Ticket Status",
  Text_TicketStatus : "Ticket Status",
  Text_Tickets : "Tickets",
  Text_Inventory : "Inventory",
  Text_CreateModify : "Create/Modify",
  Text_Policy : "Policy",
  Text_Description : "Description",
  Text_Live : "Live",
  Text_OnHold : "On Hold",
  Text_InventoryNumberAvailable : 'Available',
  Text_InventoryNumberLocked : 'Locked',
  Text_InventoryNumberSold : 'Sold',
  Text_InventoryNumberTotal : 'Total',
  Text_InventoryMaxStockAllowed : 'You are trying to add too many items, the maximum number of items you are can add is : {0}',
  Text_InventoryMaxRemovekAllowed : 'Currently you can only remove up to {0} items',
  Text_AddRemoveInventoryItemTitlePopup : [
      'Add Inventory Items', 'Remove Inventory Items'
  ],
  Text_Disclaimer : "DISCLAIMER",
  Msg_Disclaimer : "By use of this ticket, the ticket purchaser/holder (\"Holder\") agrees that: (a) he or she shall not transmit or aid in transmitting any information about the game to which it grants admission, including, but not limited to, any account, description, picture, video, audio, reproduction or other information concerning the game (collectively \"Game Information\");",
  Error_ParseProvider : 'We could not recognize the social address, please review and try again',
  SuccessVenue : "You have updated venue successfully",
  Text_CreateSuccessVenue : "You have created venue successfully",
  Text_NoVenueMsg : "Currently there are no venues for this store.",
  Msg_UnableToLogin : "Unable to login, please try again later.",
  Page_Index : '',
  Page_ConsumerRegStep1 : 'Sign-Up Step 1',
  Page_ConsumerRegStep2 : 'Sign-Up Step 2',
  Page_ConsumerRegStep3 : 'Sign-Up Step 3',
  Page_Login : 'Login',
  Page_ContactUs : 'Contact Us',
  Page_Shopcart : 'Shopping Cart',
  Page_Checkout : 'Checkout',
  Page_SchoolAccount : 'School Account',
  Page_MyAccount : 'My Account',
  Page_RefundPolicy : 'Refund Policy',
  Page_SchoolZone : 'School Zone',
  Page_Terms : 'Terms',
  Page_PrivacyPolicy : 'Privacy Policy',
  Page_About : 'About Us',
  Page_TicketsSearch : 'Tickets',
  Page_BuyTickets : 'Buy Tickets',
  Page_PageNotFound : 'Page not found',
  Text_BuyerName : "I'm buyer",
  Text_StoreOwnerName : "I'm administrator",
  Text_Ask : 'Ask',
  Text_Congrats : 'Congratulations!',
  Text_WizardComplete : 'You have succesfully completed this wizard. Your changes have been saved.',
  Text_Registration : "Registration",
  Text_DateOfBirth : "Date of birth",
  Text_Sex : "Sex",
  Text_Email : "E-mail",
  Text_CustomURI : "URL Alias Name",
  Text_TipCustomURI : "Example: my-beautiful-store",
  Text_CustomURIUnavailable : "This URL has been taken",
  Text_ReEmail : "Re-enter E-mail",
  Text_SignUpService : "Sign Up with existing service",
  Text_CreateAccount : "OR create an account",
  Text_UpdateAddress : "Your address has been updated.",
  Text_ManageVenue : "Manage Venue",
  Text_VenueType : "Venue Name",
  Text_Location : "Location",
  Text_LocationInfo : "Location Details",
  Text_Admin : "Admin",
  Text_CreateVenue : "Create Venue",
  Text_CreateStore : "Create Store",
  Text_CreateStore_Step1 : "Step 1: Information",
  Text_CreateStore_Step2 : "Step 2: Location",
  Text_CreateStore_Step3 : "Step 3: Accounting",
  Text_Finished : "Finished",
  Text_Address : 'Address',
  Text_UploadImage : 'Upload Images. Ensure you upload the higest quality version you have. Accepted formats are gif, jpg and png. Maximum file size is 10MB.',
  Text_ScannerName : "Scanner Name",
  Text_OSVersion : "OS Version",
  Text_Lastsyncdate : "LastSyncDate",
  Text_ATsVersion : "ATs Version",
  Text_NoScanDevice : "Currently there are no scan devices for this store.",

  Text_RegistrationStep0 : "Service Aggreement",
  Text_RegistrationStep1 : "Store Information",
  Text_RegistrationStep2 : "Administrator Contact Information",
  Text_RegistrationStep3 : "Payment Providers",
  Text_RegistrationStep4 : "Completed",

  Text_AdminContact_Description : "Please ensure that the following information is correct, we will only contact you when necessary and we will not share your information with any 3rd party for any reason.",
  Text_Payment_Description : "In order to collect payments you must add and configure payment gateway.",
  Text_Payment : "Payment Providers",
  Text_Completed_Description : "Thank you for creating your store, we will now take you to your store where you can continue to customize and add events and tickets.",
  Text_Paypro_AuthorizeNet : 'Authorize.Net',
  Text_Paypro_MockPayment : 'Mock Payment',
  Text_Paypro_Moneris : 'Moneris',
  Text_Paypro_NoPayment : 'Without Payment',
  Text_Paypro_PayPal : 'PayPal'
};
