var ScannerResources = {        
    Text_ConfirmDeleteDevice: 'Are you sure want to delete this device?',
    Text_UpdateDeviceSuccess: 'The device has been updated successfully.',
    Text_CreateDeviceSuccess: 'The device has been created successfully.',
    Text_UnRegisterSuccess: 'The device has been un-registered',
    Text_ActiveDevice: 'Are you sure want to active this device?',
    Text_DeactiveDevice: 'Are you sure want to deactive this device?',
    Text_UnregisterDevice: 'Are you sure want to unregister device?',
    Text_UpdateDevice: 'Are you sure want to update this device?',
    Text_CodeDevicePopup: 'Device',
    Text_ShouldRegister: "This device is currently not registered.  To register your iPhone or Android device, install and start the AzureTickets Scanner software on to your device and scan the following QR Code.",
    Text_AddDevice: "Add Device",
    Text_Unregistered: "Unregistered",
    Text_ScannerName: "Scanner Name",
    Text_DeviceName: "Device Name",
    Text_Hardware: "Hardware",
    Text_OSVersion: "OS Version",
    Text_LastSyncDate: "Last Sync Date",
    Text_ATsVersion: "ATs Version",
    Text_NoEventScanner_Msg : 'Currently there are no scanners for this event.',
    Text_NoScanner_Msg : 'Currently there are no scanners registered.'
}